# Generated by Django 3.2.4 on 2021-06-23 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 23, 36, 14, 54924), verbose_name='Дата публикации'),
        ),
    ]
