# Generated by Django 3.2.4 on 2021-06-23 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_alter_test_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 23, 39, 5, 573349), verbose_name='Дата публикации'),
        ),
    ]
