# Generated by Django 3.2.4 on 2021-06-23 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_alter_test_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeruser',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_user', to='test.answer'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 0, 0, 16, 536217), verbose_name='Дата публикации'),
        ),
    ]
