# Generated by Django 3.2.4 on 2021-06-23 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_auto_20210624_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeruser',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='test.answer'),
        ),
        migrations.AlterField(
            model_name='answeruser',
            name='test_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers_user', to='test.testresult'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 0, 2, 45, 113361), verbose_name='Дата публикации'),
        ),
    ]
