# Generated by Django 3.2.4 on 2021-06-24 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_auto_20210624_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 13, 58, 44, 127618), verbose_name='Дата публикации'),
        ),
    ]
