# Generated by Django 3.2.4 on 2021-06-27 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_alter_test_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 20, 48, 42, 306745), verbose_name='Дата публикации'),
        ),
    ]
