# Generated by Django 3.2.4 on 2021-06-28 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0013_alter_test_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='count_correct',
            field=models.IntegerField(default=0, verbose_name='Кол-во правильных ответов'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='count_incorrect',
            field=models.IntegerField(default=0, verbose_name='Кол-во неправильных ответов'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Кол-во баллов за ответ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 57, 1, 501690), verbose_name='Дата публикации'),
        ),
    ]
