# Generated by Django 3.2.4 on 2021-06-28 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0015_auto_20210628_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeruser',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 23, 9, 38, 318878), verbose_name='Дата публикации'),
        ),
    ]
