# Generated by Django 3.2.4 on 2021-06-28 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0016_auto_20210628_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 23, 10, 21, 801952), verbose_name='Дата публикации'),
        ),
    ]
