# Generated by Django 3.2.4 on 2021-06-28 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0018_alter_test_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 23, 38, 5, 492502), verbose_name='Дата публикации'),
        ),
    ]
