# Generated by Django 3.2.4 on 2021-07-04 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0020_alter_test_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 19, 32, 36, 261151), verbose_name='Дата публикации'),
        ),
    ]
