# Generated by Django 3.2.4 on 2021-06-26 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hometask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255, verbose_name='Задание')),
                ('description', models.CharField(max_length=255, verbose_name='Описание ДЗ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometask_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedHometask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_txt', models.FileField(blank=True, upload_to='homeTasks/', verbose_name='Файл с ДЗ')),
                ('mark', models.IntegerField(blank=True, verbose_name='Оценка')),
                ('comment_admin', models.CharField(blank=True, max_length=255, verbose_name='Комментарий по дз от админа')),
                ('completed', models.BooleanField(default=False)),
                ('date_finished', models.DateTimeField(blank=True, verbose_name='Дата сдачи')),
                ('hometask', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hometask.hometask')),
            ],
            options={
                'verbose_name': 'Результат дз',
                'verbose_name_plural': 'Результаты дз',
            },
        ),
    ]
