# Generated by Django 3.2.4 on 2021-06-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0002_auto_20210626_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedhometask',
            name='hometask',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hometask', to='hometask.hometask'),
        ),
    ]
