# Generated by Django 3.2.4 on 2021-06-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0003_alter_completedhometask_hometask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedhometask',
            name='mark',
            field=models.IntegerField(null=True, verbose_name='Оценка'),
        ),
    ]
