# Generated by Django 3.2.4 on 2021-06-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometask', '0004_alter_completedhometask_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedhometask',
            options={'verbose_name': 'Результат ДЗ', 'verbose_name_plural': 'Результаты ДЗ'},
        ),
        migrations.AlterModelOptions(
            name='hometask',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
    ]
